### ISSUE TITLE
BottomSheet crashes on Dismiss (Android, nativescript-angular)

### ISSUE THREAD

**Issue by hamidbsd** [Akylas/nativescript-material-components#71]
Which platform(s) does your issue occur on?
- Android 
- Any versions 
- What type of device? any 

Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.1.2
- Runtime: tns-android 6.1.2
- Plugin(s): Angular 8.2.11, nativescript-material-components 2.5.2

Please, tell us how to recreate the issue in as much detail as possible. 
Can be reproduced using any generic usage of the plugin like the nativescript-angular demo of the BottomSheet 

Is there any code involved? 
This is how the crash log looks like:

```
An uncaught Exception occurred on "main" thread.
Calling js method onDismiss failed
TypeError: Cannot read property 'setOnTouchListener' of null

StackTrace:
	push.../node_modules/tns-core-modules/ui/core/view/view.js.View.onUnloaded(file:///data/data/app.name/files/app/vendor.js:102970:38)
	at (file:///data/data/app.name/files/app/vendor.js:101093:92)
	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///data/data/app.name/files/app/vendor.js:101082:9)
	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.callUnloaded(file:///data/data/app.name/files/app/vendor.js:101093:14)
	at push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase.unloadView(file:///data/data/app.name/files/app/vendor.js:101222:18)
	at (file:///data/data/app.name/files/app/vendor.js:101024:19)
	at push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///data/data/app.name/files/app/vendor.js:110064:26)
	at push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/app.name/files/app/vendor.js:102584:14)
```

**Comment by farfromrefug** [comment]
@hamidbsd cannot really help you without an example to reproduce. Plus your error actually happens in {N} and not in this module.

**Comment by farfromrefug** [comment]
@hamidbsd Please post that issue on {N} repo with a link to this one. I am almost sure it is a {N} bug. And i already know where.

**Comment by johny8228** [comment]
@farfromrefug I'm experiencing the same issue.I did some research and apparently on the NS Team side a similar issue was fixed for the modal component. In my project, I'm using both NS modal component but also Material bottomsheet component, the modal component works fine now but the bottomsheet crashes.For th modal component the fix was merged here https://github.com/NativeScript/NativeScript/pull/6723/files

I wonder if it's not the same issue and the fix for the bottomsheet crash should be made in the bottomsheet.android.ts file. Maybe this can help you.

**Comment by Firetrip** [comment]
We have the same issue. Is there a way to work around this?

**Comment by romandragan** [comment]
Same for me.

**Comment by hamidbsd** [comment]
I have reported this on {N} repo as well based on @farfromrefug 's suggestion.
https://github.com/NativeScript/NativeScript/issues/8038

The only work around I could come up with is to avoid capturing (touch) and work with (tap) where possible for the time being.

**Comment by johny8228** [comment]
In my opinion, it could be an issue in the material component itself and not {N} repo related. Please see my previous comment.

**Comment by hamidbsd** [comment]
@farfromrefug where you able to check if this is the same problem as this one?
https://github.com/NativeScript/NativeScript/pull/6723

**Comment by farfromrefug** [comment]
@hamidbsd i released a beta version 3.0.0. Can you test it? Be careful though it requires ```@nativescript```

**Comment by hamidbsd** [comment]
@farfromrefug just built with 3.0.0. The problem still exists.
Here is the StackTrace

```
An uncaught Exception occurred on "main" thread.
Calling js method onDismiss failed
TypeError: Cannot read property 'setOnTouchListener' of null

StackTrace:
push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onUnloaded(file:///data/data/my.app/files/app/vendor.js:80449:38)
	at (file:///data/data/my.app/files/app/vendor.js:78571:92)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///data/data/my.app/files/app/vendor.js:78560:9)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callUnloaded(file:///data/data/my.app/files/app/vendor.js:78571:14)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.unloadView(file:///data/data/my.app/files/app/vendor.js:78700:18)
	at (file:///data/data/my.app/files/app/vendor.js:78502:19)
	at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///data/data/my.app/files/app/vendor.js:87545:26)
	at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/my.app/files/app/vendor.js:80062:14)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onUnloaded(file:///data/data/my.app/files/app/vendor.js:78501:14)
	at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onUnloaded(file:///data/data/my.app/files/app/vendor.js:80455:37)
	at (file:///data/data/my.app/files/app/vendor.js:78571:92)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///data/data/my.app/files/app/vendor.js:78560:9)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callUnloaded(file:///data/data/my.app/files/app/vendor.js:78571:14)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.unloadView(file:///data/data/my.app/files/app/vendor.js:78700:18)
	at (file:///data/data/my.app/files/app/vendor.js:78502:19)
	at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///data/data/my.app/files/app/vendor.js:87545:26)
	at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/my.app/files/app/vendor.js:80062:14)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onUnloaded(file:///data/data/my.app/files/app/vendor.js:78501:14)
	at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onUnloaded(file:///data/data/my.app/files/app/vendor.js:80455:37)
	at (file:///data/data/my.app/files/app/vendor.js:78571:92)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///data/data/my.app/files/app/vendor.js:78560:9)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callUnloaded(file:///data/data/my.app/files/app/vendor.js:78571:14)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.unloadView(file:///data/data/my.app/files/app/vendor.js:78700:18)
	at (file:///data/data/my.app/files/app/vendor.js:78502:19)
	at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///data/data/my.app/files/app/vendor.js:87545:26)
	at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/my.app/files/app/vendor.js:80062:14)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onUnloaded(file:///data/data/my.app/files/app/vendor.js:78501:14)
	at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onUnloaded(file:///data/data/my.app/files/app/vendor.js:80455:37)
	at (file:///data/data/my.app/files/app/vendor.js:78571:92)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///data/data/my.app/files/app/vendor.js:78560:9)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callUnloaded(file:///data/data/my.app/files/app/vendor.js:78571:14)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.unloadView(file:///data/data/my.app/files/app/vendor.js:78700:18)
	at (file:///data/data/my.app/files/app/vendor.js:78502:19)
	at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///data/data/my.app/files/app/vendor.js:87545:26)
	at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///data/data/my.app/files/app/vendor.js:80062:14)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onUnloaded(file:///data/data/my.app/files/app/vendor.js:78501:14)
	at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onUnloaded(file:///data/data/my.app/files/app/vendor.js:80455:37)
	at (file:///data/data/my.app/files/app/vendor.js:78571:92)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///data/data/my.app/files/app/vendor.js:78560:9)
	at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callUnloaded(file:///data/data/my.app/files/app/vendor.js:78571:14)
	at BottomSheetDialogFragmentImpl.onDismiss(file:///data/data/my.app/files/app/vendor.js:106136:23)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.gen.com.google.android.material.bottomsheet.BottomSheetDialogFragment_vendor_106066_32_BottomSheetDialogFragmentImpl.onDismiss(BottomSheetDialogFragment_vendor_106066_32_BottomSheetDialogFragmentImpl.java:26)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1520)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by farfromrefug** [comment]
@hamidbsd so i guess it is not the same issue as this one NativeScript/NativeScript#6723

**Comment by hamidbsd** [comment]
@farfromrefug this might be helpful. It happens only when the bottomsheet is dismissed(without closeCallback being called) or calling closeCallback(false). When closeCallback is called with non-null value it works as expected.

**Comment by farfromrefug** [comment]
Can you create a sample project not using angular? That would he;p a lot!

**Comment by hamidbsd** [comment]
@farfromrefug please find below a very simple project which could be built with {N} 6.2.1 + MaterialBottomsheet 3.0.0 (you can remove angular as you wish)
https://www.dropbox.com/s/m1weedpegpo0rlv/Bottomsheet%20crashing.zip?dl=0

**Comment by hamidbsd** [comment]
@farfromrefug I posted the solution you suggested to fix the problem in {N} repo but due to being an edge case, I am not sure if it is gonna make it to any coming releases. 
https://github.com/NativeScript/NativeScript/issues/8038#issuecomment-557918528

Would you consider overriding {N}'s `onUnloaded()`  in the plugin with the little patch to fix the problem for the time being?

**Comment by farfromrefug** [comment]
@hamidbsd already done in 3.0.1. If you still have the issue then it is not a fix

**Comment by hamidbsd** [comment]
@farfromrefug I had no idea about the fix in 3.0.1. I was still on 3.0.0.
Just tested and can confirm the bug has been fixed with this commit https://github.com/Akylas/nativescript-material-components/commit/171dd76b6b32ceff56ed1c394bddbfb4aafd9d35

Thanks.

**Comment by hamidbsd** [comment]
@farfromrefug well, I still had the patch
https://github.com/NativeScript/NativeScript/issues/8038#issuecomment-557918528

in my built and without it, the problem still exist. (nativescript-material-bottomsheet@3.0.2)
