### ISSUE TITLE
[3.0.0] - Build error in android

### ISSUE THREAD

**Issue by fvdung** [Akylas/nativescript-material-components#86]
tns-android 6.2.0
@nativescript/core 6.2.1

I get error log from terminal

```
* What went wrong:
Execution failed for task ':verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/.../platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:4:5-10:13: AAPT: error: style attribute 'attr/backgroundColor (aka org.nativescript.nativescript_material_textfield:attr/backgroundColor)' not found.

     /Users/.../platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:17:5-30:13: AAPT: error: style attribute 'attr/materialThemeOverlay (aka org.nativescript.nativescript_material_textfield:attr/materialThemeOverlay)' not found.

     /Users/.../platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:17:5-30:13: AAPT: error: style attribute 'attr/boxBackgroundColor (aka org.nativescript.nativescript_material_textfield:attr/boxBackgroundColor)' not found.

     /Users/.../platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:17:5-30:13: AAPT: error: style attribute 'attr/boxBackgroundMode (aka org.nativescript.nativescript_material_textfield:attr/boxBackgroundMode)' not found.

     /Users/...o/platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:17:5-30:13: AAPT: error: style attribute 'attr/boxCollapsedPaddingTop (aka org.nativescript.nativescript_material_textfield:attr/boxCollapsedPaddingTop)' not found.

     /Users/.../platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:17:5-30:13: AAPT: error: style attribute 'attr/boxCornerRadiusTopStart (aka org.nativescript.nativescript_material_textfield:attr/boxCornerRadiusTopStart)' not found.

     /Users/.../platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:17:5-30:13: AAPT: error: style attribute 'attr/boxCornerRadiusTopEnd (aka org.nativescript.nativescript_material_textfield:attr/boxCornerRadiusTopEnd)' not found.

     /Users/.../platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:17:5-30:13: AAPT: error: style attribute 'attr/boxCornerRadiusBottomStart (aka org.nativescript.nativescript_material_textfield:attr/boxCornerRadiusBottomStart)' not found.

     /Users/...o/platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:17:5-30:13: AAPT: error: style attribute 'attr/boxCornerRadiusBottomEnd (aka org.nativescript.nativescript_material_textfield:attr/boxCornerRadiusBottomEnd)' not found.

     /Users/.../platforms/tempPlugin/nativescript_material_textfield/src/main/res/values/textfieldstyles.xml:11:5-13:13: AAPT: error: style attribute 'attr/editTextStyle (aka org.nativescript.nativescript_material_textfield:attr/editTextStyle)' not found.
```

**Comment by farfromrefug** [comment]
@fvdung seems like a build issue. Can you cleanup all?

**Comment by fvdung** [comment]
I removed platforms, hooks, node_modules folder.
I’m using Nativescript-Vue

**Comment by farfromrefug** [comment]
@fvdung sorry i found the issue. Will fix right away!
Thanks

**Comment by fvdung** [comment]
@farfromrefug After updating to version 3.0.1, I encountered an error that appeared in 2.5.3
```
Execution failed for task ':app:mergeDebugResources'.
Android resource compilation failed
/Users/dudu/.gradle/caches/transforms-2/files-2.1/72298b7c3ba35f49568fe7fb8247d7b6/TNSChart-release/res/values/values.xml:71:5-85:25: AAPT: error: duplicate value for resource 'attr/horizontalOffset' with config ''.

/Users/dudu/.gradle/caches/transforms-2/files-2.1/72298b7c3ba35f49568fe7fb8247d7b6/TNSChart-release/res/values/values.xml:71:5-85:25: AAPT: error: resource previously defined here.

/Users/dudu/.gradle/caches/transforms-2/files-2.1/72298b7c3ba35f49568fe7fb8247d7b6/TNSChart-release/res/values/values.xml:71:5-85:25: AAPT: error: duplicate value for resource 'attr/verticalOffset' with config ''.

/Users/dudu/.gradle/caches/transforms-2/files-2.1/72298b7c3ba35f49568fe7fb8247d7b6/TNSChart-release/res/values/values.xml:71:5-85:25: AAPT: error: resource previously defined here.

/Users/dudu/code/zeko/zeko/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.
```

**Comment by farfromrefug** [comment]
@fvdung yes that s another issue. It s been fixed in nativescript-ui-chart @next

**Comment by fvdung** [comment]
@farfromrefug this problem still exists with the element BottomNavigation of {N}
[https://github.com/Akylas/nativescript-material-components/issues/76#issuecomment-547721963](https://github.com/Akylas/nativescript-material-components/issues/76#issuecomment-547721963)
You think that there is a problem with android runtime. But in version 2.5.2 I did not have the same problem, only when updating from 2.5.4 or later did the problem arise
```
System.err: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5269)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:5090)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:5030)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:5003)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
System.err: 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
System.err: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
System.err: 	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7156)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by farfromrefug** [comment]
@fvdung you mix up things. The log you are showing do not tell me much and has nothing to do with the other issue. As I don't get it right now I can't fix it yet

**Comment by fvdung** [comment]
Oh sorry! I'll close this issue and created a new issue!
